### ISSUE TITLE
::fsm/on-enter subject to race condition

### ISSUE THREAD

**Issue by brjann** [ingesolvoll/kee-frame#100]
(def my-http-request-fsm
       {:id    :my-http-request
       :start ::loading
       :stop  ::loaded
       :fsm   {::waiting        {[::go] {:to ::loading}}
               ::loading        {[::fsm/on-enter]      {:dispatch [[:contact-the-server]]}
                                 [:server-responded]   {:to ::loaded}
                                 [:default-on-failure] {:to ::loading-failed}}
                ::loading-failed {[::fsm/timeout 10000] {:to ::loading}}}})

If `::go` and `:server-responded` are dispatched within a very short interval (not likely in this example), then the `::fsm/on-enter` dispatch is never executed. It seems that kee-frame handles the event change before it handles `::fsm/on-enter`

**Comment by ingesolvoll** [comment]
@brjann Thanks for reporting! I think I can see where the error is. I implemented on-enter as a timeout with 0 delay. Convenient, but wrong. See:

https://github.com/ingesolvoll/kee-frame/blob/dfe5acb1e638bb656fe7193f2c805a45026010eb/src/kee_frame/fsm/alpha.cljc#L59

**Comment by brjann** [comment]
@ingesolvoll: Happy to contribute!

I believe you are right. The on-enter should be dispatched right away instead of as a timeout. I would have been happy to help out with a patch, but I haven't quite understood how the return from the `::start` method works. https://github.com/ingesolvoll/kee-frame/blob/dfe5acb1e638bb656fe7193f2c805a45026010eb/src/kee_frame/fsm/alpha.cljc#L110-L113

 My naïve idea would be that a `{:dispatch [on-enter-event]}` should be included in the return.
