### ISSUE TITLE
Config option for specifying other dispatch handlers than http on-success

### ISSUE THREAD

**Issue by ingesolvoll** [ingesolvoll/kee-frame#12]

**Comment by mudgen** [comment]
I found your project today from Daniel Compton's REPL newsletter. I really like this project and I am going to use it in my re-frame web app starting tomorrow.

I am using effect handlers from the re-frame-web3-fx project (https://github.com/district0x/re-frame-web3-fx). I'd like like to use the event chains feature with this. When will the inference algorithm be configurable? I'm not demanding you to do anything and I really appreciate what you have done. I'd just like to know the status of configuring this functionality. 

Great to see this work.

**Comment by ingesolvoll** [comment]
I actually made a potentially working version of this last night. It's great to hear that you like the lib and want to test it out.

I was thinking about possible use cases for configuring chain linking, I worked with web3-fx before so that was on my mind.

Maybe you could try out the `0.2.0-SNAPSHOT` and see if those changes float your boat? You would have to add configuration like this:

```clojure
;; An example from web3
(reg-event-fx
  ::get-token-total-supply
  (fn [{:keys [:db]}]
    {:web3/call {:web3 (:web3 db)
                 :fns [{:instance (:token-contract-instance db)
                        :fn :total-supply
                        :on-success [::token-total-supply-result]
                        :on-error [::error]}]}}))

;;You would need this config for kee-frame
(k/start! {:chain-links [[:web3/call :fns 0 :on-success]]
              :routes         routes})
```

We can both see that the current config is not very good, using 0 to point at the first item in some list. I'm working on refactoring the chain stuff, as it is complex and messy. Probably need some days, possibly weeks, for that.

Please let me know how it's going!

**Comment by ingesolvoll** [comment]
My experience from working with web3-fx is that you quickly enter into callback hell. So I can understand that you're intrigued by using chains for this. It's not straightforward to design a configuration for this that is generic enough, so some help from you would be great. I would need some real-world examples of typical use cases.

**Comment by ingesolvoll** [comment]
I think I'm on to something, been working on this yesterday and today. Circling in on a config looking like this:

```clojure
{:present?   (fn [effects] (:http-xhrio effects))
                   :dispatched (fn [effects] (get-in effects [:http-xhrio :on-success]))
                   :path       [:http-xhrio :on-success]}
```

Any input is appreciated!

**Comment by mudgen** [comment]
Cool. I like the first configuration. What are the :dispatched and :path items in the config? What do they do?

**Comment by mudgen** [comment]
Can you explain how this config works:

```
{:present?   (fn [effects] (:http-xhrio effects))
  :dispatched (fn [effects] (get-in effects [:http-xhrio :on-success]))
  :path       [:http-xhrio :on-success]}
```

**Comment by ingesolvoll** [comment]
Not sure I want to solve the problem of `:fns`. If you have a clever idea, please let me know :)

**Comment by ingesolvoll** [comment]
I chose the map of functions for this API because it is much more flexible than just a vector. I think it's ok that it's more verbose, as it is very limited in scope and size. 

The vector wouldn't work for web3-fx, because it naively assumes that the first element of the vector is enough to sniff the existence of the effect, like `:http-xhrio`.

**Comment by ingesolvoll** [comment]
The 0.2.0-SNAPSHOT should have few or no bugs at this time, please check it out and let me know if this API works for you. I will probably release it within a few days.

**Comment by mudgen** [comment]
@ingesolvoll I'm trying out 0.2.0-SNAPSHOT. I'll let you know how it goes.
