### ISSUE TITLE
Document relation to server side routing

### ISSUE THREAD

**Issue by lsnape** [ingesolvoll/kee-frame#21]
When integrating kee-frame into my own project I noticed that refreshing the browser after the navigation had changed didn't work. I quickly realised it was because my server routes did not have knowledge of my UI routes definition.

IIRC your kee-frame demo project effectively ignores the URI and returns the index.html to every GET request. The controllers then dispatch events accordingly to initialise the app. More typically, however, the server may also define API routes, and also return a 404 page if the route doesn't match.

The way I solved this problem was to define my routes in a cljc file and to include them in the server routes definition, like so:

``` clojure
(defn api-routes
  []
  {"sample" :api/sample})

(def ui-routes
  {"" :intro
   "about" :about})

(defn build-ui-routes
  []
  (walk/postwalk #(if (keyword? %) :index %) ui-routes))

(defn build-routes
  [{:keys [api-version] :as info}]
  ["/"
   (concat
    [[#{"" "index.html"} :index]
     ["ping"             :ping]
     ["public/"          :public]
     ["healthcheck"      :healthcheck]
     ["info"             :info]
     [["api/v" :api-version] {"/" (api-routes)}]]
    (build-ui-routes)
    [[true :not-found]])])
```
The `postwalk` transformation is necessary for the backend to return the index.html for any of the defined UI routes. Does this seem like a reasonable solution? If so maybe a description in the docs would be helpful to others.

This is a great little library BTW. Thanks for taking the time to write it.

**Comment by ingesolvoll** [comment]
Hi! Thanks for posting back :)

You are right, documentation about how to coordinate routing on server and client is absent. I want kee-frame to be a complete solution for getting quickly up and running, so this needs some work.

I like your solution with cljc, I guess you need something like that if you want to be more specific about when to bypass server routing and forward it to the client.

The intention of the sample project is not to ignore the URI. The way I normally do it is to match server urls first, and fall back to index.html on anything that is not found. This is of course not optimal as routes that should normally be 404 will render as index.html. But a fair trade off for simple apps. You can still use a 404 handler in the client, if the route is still not found there.

Another technique is to use things like /api and /client, so anything under /client matches as index.html on the server.

I don't really know if people actually settled on any "best practice" for this, so not sure what to recommend. But definitely need to include it in the README!

**Comment by lsnape** [comment]
Falling back to index.html and customising the 404 page in the javascript is a perfectly good solution. And since the server requires no knowledge of the UI routes is simpler too. If guidance was provided in the README I would favour this approach over mine, with perhaps a mention of how alternate static pages might be served, with reference to something like the code example above.

Prepending UI routes with /client would also work, but at the expense of making it visible to the customer-facing URLs.

**Comment by ingesolvoll** [comment]
Let's keep this open, I would like to be reminded to document this.

**Comment by lsnape** [comment]
FWIW I found a bug with my `postwalk` implementation: bidi's route params also match the `keyword?` predicate. I've switched to the implementation where `:index` is matched if none of the server routes matched, and show a 404 when the UI routes don't match.
