### ISSUE TITLE
Support both browser and hash history

### ISSUE THREAD

**Issue by ingesolvoll** [ingesolvoll/kee-frame#23]

**Comment by ingesolvoll** [comment]
Kee-frame uses browser history now, with urls like `/some/path`. It would be nice to also support has based (`#/some/path`), as they are needed for serverless apps.

I don't know how to configure this for accountant and bidi, and I don't have any motivation to do so myself because I use browser history. That's why I marked it as help wanted.

**Comment by mudgen** [comment]
I see, makes sense. Currently how knee-frame is setup with bidi and accountant is perfect for me, but I can see the need for hash based URLs for serverless apps. I think it is a good idea to ask for help on this because I can see someone who wants to make a serverless app wanting to help with this.
