### ISSUE TITLE
:navigate-to requires wrapping path-vector in vector

### ISSUE THREAD

**Issue by eidekrist** [ingesolvoll/kee-frame#28]
router.cljc specifies the fx-handler :navigate-to on line 34:
`(rf/reg-fx :navigate-to #(apply goto %))`

This means that the path vector must be wrapped in an additional vector:
`{:navigate-to [[:blabla/index :bla 123]]}`

**Comment by ingesolvoll** [comment]
Thank you for reporting on the bleeding edge!

Committed a fix that might work. Feature was not in use in sample app, so did not notice this.
