### ISSUE TITLE
Dispatch Multiple Events From a Controller

### ISSUE THREAD

**Issue by mudgen** [ingesolvoll/kee-frame#31]
It would be nice/useful to be able to dispatch multiple events from the :start function of a controller.

Something like this:

```
(reg-controller :leagues
                {:params (constantly true)
                 :start  [[:leagues/load] [:leagues/something-else]]})
```

My use case is that I want to dispatch multiple events when the homepage first loads. Or is there an alternative/better way to do this?

**Comment by ingesolvoll** [comment]
You can make several different controllers triggering from the same params.  So your homepage could have 5 controllers. The downside is that you can't control the order, but that's usually not a problem.

Alternatively, dispatch to an event that can do multiple dispatch from there.

**Comment by ingesolvoll** [comment]
Just to be clear about what I mean:


```clojure
(reg-controller :leagues
                {:params (constantly true)
                 :start      [:leagues/load]})

(reg-controller :leagues
                {:params (constantly true)
                 :start      [:leagues/something-else]})
```

**Comment by mudgen** [comment]
Yes, that is how I am doing it currently. Thanks.

**Comment by ingesolvoll** [comment]
Probably won't change this. But thanks for highlighting the issue, it's an interesting one!
