### ISSUE TITLE
reg-event-fx doesn't take interceptors as an argument

### ISSUE THREAD

**Issue by mudgen** [ingesolvoll/kee-frame#32]
The re-frame version of reg-event-fx is able to take 3 arguments.  It is able to take a vector of interceptors.

I need to add some interceptors to some of my events, but I can't because the knee-frame version of reg-event-fx doesn't take interceptors as an argument.

Can interceptor arguments to reg-event-fx be added?  

So far working with kee-frame is great.

**Comment by mudgen** [comment]
Looks like I can just use regular re-frame reg-event-fx functions, since the kee-frame one just adds interceptors for debugging and spec. I will do that.

**Comment by ingesolvoll** [comment]
You're right! The only reason to use kee-frame versions of reg-event-* is to get the special interceptors. You are free to use the regular ones if you don't need the interceptors.

**Comment by ingesolvoll** [comment]
But you are right. There's no reason for those to not take interceptors as an argument. I made a version that merges default interceptors with arguments.

**Comment by mudgen** [comment]
Great!
