### ISSUE TITLE
Explain chain-links Config Further

### ISSUE THREAD

**Issue by mudgen** [ingesolvoll/kee-frame#33]
I am a little unclear on how the :explicit-dispatch config works and how it affects things.

> ;;  Was the dispatch for this effect already set? Then return the value
>   :explicit-dispatch (fn [effects] (get-in effects [:http-xhrio :on-success]))

What does this do?

**Comment by ingesolvoll** [comment]
Maybe the names are not that optimal?

`explicit-dispatch` is basically `get-dispatch`, while `insert-dispatch` is `set-dispatch`. Does that make it clearer?

**Comment by mudgen** [comment]
Okay.  If explicit-dispatch/get-dispatch finds a value then is insert-dispatch still used?

If explicit-dispatch finds the next  event to dispatch then in that case does an insert-dispatch need to be configured?

**Comment by ingesolvoll** [comment]
This is simpler than you think :) The things you are asking are implementation details in the framework.

All that's needed from you is information about how to read and write dispatch values for a certain effect. That's what those functions are.

**Comment by mudgen** [comment]
Okay

**Comment by mudgen** [comment]
Are all three chain-links keys (:present?, :dispatched?, :insert) required? In all cases do I need to use all three? What does the :dispatched? key do? Why is it needed?

**Comment by ingesolvoll** [comment]
From your questions, I sense that we might be talking about different things. The answer to what your asking is very simple and I don't know how to express it differently. Maybe you could give me an example of what you're trying to do?

**Comment by mudgen** [comment]
I am trying to understand why I need a "get-dispatch" key at all.

I understand that the "effect-present?" key is there to say that the map configuration is for a specific effect.

I understand that the "set-dispatch" key is there to say where in the effect map the next dispatch should be inserted.

I understand those two keys and why I supply configuration for them. Those two keys seem to me to be all that you need to configure an effect.

Why do we need the "get-dispatch" key? My understanding is that "get-dispatch" reads the dispatch information from the effect if it exists.  So, why do we do that? Why do we care?  Why would we put the next dispatch in the effect, isn't that the purpose of the "set-dispatch" key?  Doesn't the dispatch always go to the next event in the chain?  or not?

I feel that I may be able to more effectively use the "get-dispatch" key if I understand it, otherwise I am putting in the "get-dispatch" key just because I am supposed to, rather than wanting to because I want it to do something for me.

**Comment by mudgen** [comment]
I am able to set the `:get-dispatch` function to `(fn [effects] nil)` and my code still works, so what is the point of having `:get-dispatch` at all?

**Comment by mudgen** [comment]
Is` :get-dispatch` used when you don't want the effect to dispatch to the next event in the event chain? Is it used when you want to dispatch to an event outside the chain?  

When using reg-chain-named can ` :get-dispatch` be used to dispatch another event in the chain that is not the next one in the sequence?

**Comment by ingesolvoll** [comment]
Ok, I see. get-dispatch is used when you actually specify something like `{:on-success [:your-event-1]}` in your event handler. That's perfectly legal, and chains need to cover that case. But it might not be used in your code.

**Comment by mudgen** [comment]
Okay, so I am using reg-chain-named and I put `{:on-success [:my-specifc-event]}` in my effects in the chain.  And `:get-dispatch` is still `(fn [effects] nil)` and my code works the same, no change.

So my code works with or without `:get-dispatch`.  So when would `:get-dispatch` actually be useful? What is the use case?  I am sorry I keep asking. I would just really like to understand this.

**Comment by mudgen** [comment]
Here is my event in the chain:
```
(fn [{:keys [db]} [_ abi]]
    {:web3/call {:web3 (:web3 db)
                 :fns  [{:fn         web3-eth/contract-at
                         :args       [abi "0xe0c40018966597d57cbea226d09726750372773b"]
                         :on-success [:save-moken-contract-instance-and-watch-events]
                         :on-error   [:bad-response]}]}})
```

In my chain-link configuration I tried using this:

`:get-dispatch (fn [effects] (get-in effects [:web3/call :fns 0 :on-success]))`

And this:

`:get-dispatch (fn [effects] nil)`

And the result was the same. It looks like the use case of having` {:on-success [:my-specifc-event]}` in the effect is already covered without `:get-dispatch`.  Or is this incorrect somehow?

**Comment by ingesolvoll** [comment]
If you have no parameters to your event, it makes no difference. I guess this is your case

**Comment by mudgen** [comment]
I tested it and you are right.` :get-dispatch` allows us to pass additional arguments to the event dispatch. Cool!

Do you think it makes sense to make the `:get-dispatch` key optional in the chain-link configuration? Because it isn't needed unless additional arguments need to be added to the event dispatch.

**Comment by ingesolvoll** [comment]
I could do that, but that would slightly complicate the API. Writing all 3 functions is not much work, so I don't think it's worth it. Maybe I'll try to think of a better way to document this.

Thank you for reporting this, seeing the user side of this is very useful!

**Comment by mudgen** [comment]
Understood, thanks!
