### ISSUE TITLE
Spec doesn't match documentation for chain-link keys

### ISSUE THREAD

**Issue by mudgen** [ingesolvoll/kee-frame#34]
Documentation says this:

> [{
>   ;; Is the effect in the map?
>   :effect-present?   (fn [effects] (:http-xhrio effects)) 
>   
>   ;;  Was the dispatch for this effect already set? Then return the value
>   :explicit-dispatch (fn [effects] (get-in effects [:http-xhrio :on-success]))
>   
>   ;; Framework will call this function to insert inferred dispatch to next handler in chain
>   :insert-dispatch   (fn [effects dispatch] (assoc-in effects [:http-xhrio :on-success] dispatch))  
> }]

spec.cljc says this:

> (s/def ::chain-link (s/keys :req-un [:chain/present? :chain/dispatched? :chain/insert]))

**Comment by ingesolvoll** [comment]
Wow, that's something I didn't test. Sorry, thank you for your patience. Fixed in snapshot, did not have time to test.

**Comment by mudgen** [comment]
Thanks for fixing so quickly!

I now have event chains working beautifully with `:http-xhrio` and` :web3/call` effects.

When you have time the documentation for knee-frame needs to be updated to use :get-dispatch and :set-dispatch.
