### ISSUE TITLE
Scroll Position Lost on Back Navigation

### ISSUE THREAD

**Issue by mudgen** [ingesolvoll/kee-frame#41]
I have a website with rows of items. The user clicks on an item and looks at it and then clicks on the back button in his/her browser. When this happens the user's scroll position is lost and he/she has to re-scroll to find where they were in the rows of items.

How can I make it so that when the user clicks on the back button the user is taken back to the previous page with the previous scroll position?

**Comment by ingesolvoll** [comment]
Good question. Did not solve it myself, so I can't give you any specific hint. I'm sure there are many JS libs for it.

I would say it's outside the scope of kee-frame.

**Comment by mudgen** [comment]
Would you say it falls in the scope of Accountant?  since it is history functionality?

**Comment by ingesolvoll** [comment]
No, not really. It could be something for kee-frame, but for now I don't see a generic solution that makes sense in a framework.

It's only history functionality if it's actually navigation. Meaning that it needs to be part of the URL. It can be part of the URL as long as you update the #hash part of the URL while scrolling. In that case the back button would get you back at the right scroll position. Unless you are also using infinite scrolling :) So there's not an obvious "fits all" solution to this.

I see lots of web sites with good scroll position handling, so I'm sure there are mainstream solutions ready to be used.

**Comment by ingesolvoll** [comment]
Maybe we're not talking about the same thing then. Do you have a more specific specification for what you think kee-frame should do in this situation?

There will always be situations where persisting the scroll position on every page will NOT be desirable, and it's not always obvious how to do this for different pages within the same app.

**Comment by mudgen** [comment]
I agree that persisting the scroll position on every page will not be desirable in every situation. I just think it should work by default in the same way that a non single page application works.

Here is how a non single page application scroll position is persisted:

1. A user goes to a home web page that has many individual items on it. The user scrolls down 1200px to linked item 25 on the web page.

2. When the user clicks on the link to item 25 the scroll position 1200px is saved for the page and the page disappears and the web page for item 25 is displayed. The scroll position is automatically moved to 0 so that the top of the web page for item 25 is seen.

3. When the user clicks the back button the web page for item 25 disappears and the home web page appears. The scroll position is automatically moved to what it originally was which is 1200px.

The above example is the default way back button navigation works for scrolling in regular non single page applications. This way works very well for viewing individual items on a web page by clicking on an item and then clicking the backbutton to go back to where one was to continue looking at other items.

Check out http://newsconomy.com/ to try out this exact functionality. Newsconomy.com is a non single page application and so uses the built-in default backbutton functionality provided by the web browser.

**Comment by ingesolvoll** [comment]
I understand how this would work, and I agree that for most cases it is a good thing. For normal web browsing this is the default behavior, for SPAs it needs to be manually implemented. For example by persisting scroll position for each page in history.

Kee-frame is supposed to be a very generic framework, so we can't introduce behavior that would break some sites. So a scroll maintainer would need to be opt-in. Possibly per page.

I'll keep this issue open, maybe some inspiration pops up for a generic solution. You are more than welcome to suggest implementations if you like!

**Comment by ingesolvoll** [comment]
Seems there is some interesting material around the web about this:

https://brigade.engineering/maintaining-scroll-positions-in-all-browsers-a280d49bffca

**Comment by ingesolvoll** [comment]
Reading about the different solutions, I see that solving this in a URL-first framework is easier than the other ones. The reason is that you can maintain a map of url -> window-info. That would work with both back and forward.

**Comment by ingesolvoll** [comment]
This can be rewritten in CLJS, using such a map instead

https://github.com/brigade/delayed-scroll-restoration-polyfill/blob/master/index.es6.js

**Comment by ingesolvoll** [comment]
The map could cause some weirdness. If you browse to a certain url, then come back to it after lots of other navigation, the scroll would be restored. Might not be what you want.

**Comment by mudgen** [comment]
Yes, thanks for your insights, makes sense!

**Comment by ingesolvoll** [comment]
Turned out to be quite easy just by adding the referenced js lib as a dependency. You can check it out in the latest snapshot, seems to work for me.

**Comment by mudgen** [comment]
Cool, thanks!
