### ISSUE TITLE
How to Make Link Within Page

### ISSUE THREAD

**Issue by mudgen** [ingesolvoll/kee-frame#42]
I am wondering how to simulate a link within the same webpage using kee-frame.

For example let's say that at the bottom of a webpage I have an H1 heading called "The Story".  And at the top of the webpage I have a link to the "The Story" H1 header. So when the user clicks on the link the browser is scrolled down to the "The Story" H1 heading.

In a non-SPA website the code at the top of the webpage looks like this:
`<a href="#story">The Story</a>`

At the bottom of the webpage the code looks like this:
`<h1 id="story">The Story</h1>`

How do I achieve this same functionality using kee-frame?

**Comment by mudgen** [comment]
I found a solution. Add a data-trigger attribute to the links. It has to do with accountant.

For example:
`[:a {:href "#team" :data-trigger true} "The Team"]`

**Comment by ingesolvoll** [comment]
So you're saying that hash-links don't work because of accountant and client-side routing? Didn't know that. I didn't use hash-links on any recent project. Will check it out.

**Comment by mudgen** [comment]
Right.   The only problem with adding :data-trigger to links is that if the page is refreshed the web browser does not scroll down to the hash link location.

**Comment by ingesolvoll** [comment]
Don't know if this is fixable, will probably require me to roll my own version of accountant. Not likely to happen anytime soon, I'm afraid. Closing this, please reopen if you have ideas on how to solve it.
