### ISSUE TITLE
provide a way to always reload a controller on nav

### ISSUE THREAD

**Issue by yogthos** [ingesolvoll/kee-frame#45]
Currently, the controllers are reloaded when params change, but in some cases it would be useful to specify that the controller should always be reloaded. One workaround can be to use timestamps with something like `:params (fn [_] (js/Date.))`, but that feels a bit hacky to me. It would be nice to be able to specify something like the following:

```clojure
(reg-controller
 ::hard-refresh
 {:params ...
  :reload :always
  :start ...
  :stop ...})
```

The `:reload` key could hint that the controller should always be reloaded even if `:params` returns the same value. I think it would make sense to keep the behavior that when `:params` returns `nil`, then the controller is not started.

**Comment by ingesolvoll** [comment]
Ok, not sure I fully understand the intention.  Does reload mean that stop function should be called, followed by start? Does that also mean that `:params` should be ignored? See source code below, are you suggesting that the first statement does the same as the last if `:reload` is set to `:always`?

https://github.com/ingesolvoll/kee-frame/blob/master/src/kee_frame/controller.cljc#L44

**Comment by ingesolvoll** [comment]
So from your date example, my understanding is that you want a controller that triggers stop->start on every route change? So :params would be ignored. Am I understanding this correctly? Or do you want a controller with normal params function, but is extra eager on reloading?

**Comment by ingesolvoll** [comment]
Does this make sense? 

```clojure
(reg-controller
 ::hard-refresh
 {:params :always-reload
  :start ...
  :stop ...})
```

**Comment by ingesolvoll** [comment]
Ok, so keep the params, extra config for ignoring params and always forcing reload. Introducing `{:reload :always}` has the benefit of opening up flex for other reload options later on, I guess?

**Comment by yogthos** [comment]
Ah didn't realize the `identity` trick, that's a good work around for the moment. :) And yeah another case I can think of would be `:reload :once`, where you want the controller to start up once and only once regardless of what parameters it gets.

**Comment by ingesolvoll** [comment]
And that would be `{:params (constantly true)}`

I'm currently working on a blog post describing these little tricks.

**Comment by ingesolvoll** [comment]
The composability of the whole thing is very well thought out by Mihael in Keechma. No special features or syntax, just the basic building blocks of clojure :)

**Comment by yogthos** [comment]
Yeah the design is pretty brilliant, and it's definitely something I've been missing with plain re-frame. Things got a lot cleaner in my work project after we introduced kee-frame into it. :)

**Comment by ingesolvoll** [comment]
I'm very happy to hear that, that's my experience too. Several common frontend problems just go away.

**Comment by ingesolvoll** [comment]
http://ingesolvoll.github.io/posts/2018-06-18-kee-frame-controller-tricks/
