### ISSUE TITLE
Allow specifying interceptors on chains

### ISSUE THREAD

**Issue by SVMBrown** [ingesolvoll/kee-frame#46]
Currently `reg-chain` and `reg-chain-named` in core do not accept interceptors. Ideally, interceptors should be optional to specify, and should be able to be specified differently at each step. Could extend the spec used to conform the step fns to have an optional vector between the keyword and the fn (or before the fn if not named).

My use case is to check a user's credentials before issuing an HTTP request, and this is a case where chains are especially useful.

**Comment by ingesolvoll** [comment]
Thanks for reporting!

I will look into this. for the `-named` chains, the API starts to get messy. I would like to support this, but at the same time not make the core API to complicated for the 90% of users that only need the simple cases. Please feel free to drop in some usage examples, with suggested API, so we can discuss!

**Comment by SVMBrown** [comment]
The two options I can think of are to use the same interceptor for all, or interpose an interceptor for each one.

e.g. 1

```
(reg-chain
  :load/foo
  [auth/logged-in? (path [:path :to :foo])]
  (fn [ctx ev]
    ;; step 1
    ...)
  (fn [ctx ev]
    ;; Step 2
    ...))
```


```
(reg-chain-named
  :load/foo
  [auth/logged-in? (path [:path :to :foo])]
  (fn [ctx ev]
    ;; step 1
    ...)
  :foo/set
  (fn [ctx ev]
    ;; Step 2
    ...))
```


e.g. 2


```
(reg-chain
  :load/foo
  [auth/logged-in?]
  (fn [ctx ev]
    ;; step 1
    ...)
  [auth/audit-success (path [:path :to :foo])]  
  (fn [ctx ev]
    ;; Step 2
    ...))
```


```
(reg-chain-named
  :load/foo
  [auth/logged-in?]
  (fn [ctx ev]
    ;; step 1
    ...)
  :foo/set
  [auth/audit-success (path [:path :to :foo])]  
  (fn [ctx ev]
    ;; Step 2
    ...))
```

**Comment by ingesolvoll** [comment]
In general I would like the API of kee-frame to be as simple as possible, preferring generic lower level constructs over specific higher level ones. That will make it easier to maintain a stable API in the long term, and makes everything more composable. 

In this case, that would mean allowing interceptors per event, the same way re-frame does. It would be convenient to specify global interceptors for a chain, but it comes with the penalty of cluttering the API. It would need to be very valuable to justify it, given that it only reduces code size, not complexity.

**Comment by SVMBrown** [comment]
Well put. I agree.

**Comment by ingesolvoll** [comment]
Is this something you would consider doing as a pull request? I'm thinking about it,, but could take some time as  I'm quite busy these days.

**Comment by ingesolvoll** [comment]
I actually think I solved it. Will write some more tests, and call it a day.
