### ISSUE TITLE
The required namespace "delayed-scroll-restoration.index" is not available

### ISSUE THREAD

**Issue by cjsauer** [ingesolvoll/kee-frame#47]
_(First of all, excellent idea for a library. Thank you for sharing this.)_

I'm currently getting this error message using `[kee-frame "0.2.2"]`:

```
The required namespace "delayed-scroll-restoration.index" is not available, it was required by "kee_frame/interop.cljs"
```

_Note: I'm using shadow-cljs to build_

Reverting back to version 0.2.1 fixes the issue. 

I'm guessing that the new scroll preservation feature is the culprit? Somehow need to bundle [this foreign library](https://github.com/ingesolvoll/kee-frame/blob/master/assets/deps.cljs) into the jar file. Or if the intent is for the consumer to add this dep, could add it to the readme as well.

**Comment by ingesolvoll** [comment]
Thank you for the nice feedback!

You are right, this way of including foreign libraries is not compatible with shadow-cljs. See #43. Will soon release a new version where the import is optional

**Comment by ingesolvoll** [comment]
Releasing 0.2.3 now, please let me know if the problem persists.

I might switch the demo app to shadow-cljs, just for fun :)

**Comment by cjsauer** [comment]
@ingesolvoll updated to 0.2.3 and everything is compiling now :confetti_ball: :champagne:

**Comment by ingesolvoll** [comment]
Excellent, thanks for confirming!
