### ISSUE TITLE
allow explicitly naming events in reg-chain

### ISSUE THREAD

**Issue by yogthos** [ingesolvoll/kee-frame#5]
Having anonymous events might make debugging trickier, it would be nice to allow explicitly naming the events to make it clear what events got fired:

```clojure
(reg-chain :add-customer
            :fetch-customer-data
            (fn [_ [_ customer]]
              {:http-xhrio {:method          :post
                            :uri             "/customers"
                            :body            customer-data}})
            :set-customer-data
            (fn [{:keys [db]} [_ _ added-customer]] ;; Remember: No DB functions, only FX.
              {:db (update db :customers conj added-customer)}))
```

**Comment by yogthos** [comment]
I definitely like the idea of linking events together, this is something that can get out of hand fast unless you're disciplined in my experience.

I typically tend to opt for shorter chain as well, and  I agree that in that  case  it shouldn't be  difficult to trace them. So, I do like the option of just creating anonymous events in that case, and having the names generated.

I was thinking that having an opt-in for specifying names could be useful though. One option could be to check the args as you generate the chain, and if you see a keyword/function pair then make a  named event. Another option  could be to just provide  a  separate function like `reg-named-chain` or something.

**Comment by ingesolvoll** [comment]
Right, I was thinking the same thing. To avoid making the API too complicated I would probably prefer the separate function alternative.

**Comment by yogthos** [comment]
👍
