### ISSUE TITLE
naviagte-to with query-params

### ISSUE THREAD

**Issue by royalaid** [ingesolvoll/kee-frame#64]
Maybe I am missing something but it doesn't seem possible currently to use the internal reitit router with `:navigate-to` and query-params.

**Comment by ingesolvoll** [comment]
Thank you for reporting! I didn't have time to look into this, and never tried that myself. Do you have any ideas what would need fixing?

**Comment by MaxSt** [comment]
You can use `:navigate-to` with query-params by using the `:query-string` keyword.
Here is an example
```
:navigate-to [:example {:query-string "abc=test"}]
```

In order to produce the query string out of a map you could use a library like https://github.com/cemerick/url:
```
:navigate-to [:example {:query-string (url/map->url {"abc" "test"})}]
```

**Comment by ingesolvoll** [comment]
I will try to remember to include an example in the docs. A PR would also be appreciated and accepted :)

**Comment by ingesolvoll** [comment]
Added a link to this issue in the readme. Thanks guys!
