### ISSUE TITLE
Controller start param

### ISSUE THREAD

**Issue by bschwind** [ingesolvoll/kee-frame#67]
Hey there, thanks for the great library! I really agree with the organization of data and how everything works around the URL. I have a question about something I stumbled on and I'm not sure if it's an intentional design or not.

Let's say I have a controller for a page which loads a list of "environments", though the thing being loaded doesn't matter.:

```cljs
(k/reg-controller :environments
                  {:params (fn [{:keys [data path-params]}]
                             (when (= (:name data) :environments)
                               true))
                   :start [:environments/load params]})
```

I want to load these environments when I navigate to the `/environments` URL, and I register a chain handler:

```cljs
(k/reg-chain :environments/load
  (fn [_ _]
    (println "loading environments")
    {:http-xhrio (assoc
                   (util/http-get "/api/environments"))})

  (fn [{:keys [db]} [_ response]] ; <- Interested in this line in particular
    (println "got some environments")
    (println response)
    {:db (assoc db :environments (-> response
                                     :result))}))
```

This works all fine and dandy. However I noticed something peculiar that bugged me for quite a few days until I dug into the source to figure it out.

If the controller is defined as such:

```cljs
(k/reg-controller :environments
                  {:params (fn [{:keys [data path-params]}]
                             (when (= (:name data) :environments)
                               true))
                   :start (fn [] ; <- Note: Function instead of event vector
                            [:environments/load])})
```

Then in the HTTP success event handler, if I use the same destructuring pattern:

```cljs
(fn [{:keys [db]} [_ response]] ...)
```

Then `response` ends up being `nil`. And in fact the data returned from the HTTP request is in the first value, the `_` that we ignored.

This comes down to the difference between `start` being a vector vs. a function:

https://github.com/ingesolvoll/kee-frame/blob/06462def77c49fc7fa1e63b1cff12b41e248ba91/src/kee_frame/controller.cljc#L31-L32

So if I wanted `start` to be a function, the correct definition would be:

```cljs
(k/reg-controller :environments
                  {:params (fn [{:keys [data path-params]}]
                             (when (= (:name data) :environments)
                               true))
                   :start (fn [ctx params]
                            [:environments/load params])})
```

Maybe I don't quite understand the event chaining that kee-frame does, but is this behavior intentional? It felt a little weird that such a small change would affect code several lines down in an event handler. Obviously I should just set `:start` to a vector I want to dispatch when that's all I have, but when I was writing the code, I wanted to put some `println` statements in the `:start` function and then return the event vector, which subtly changed the behavior of HTTP response handlers.

The readme says this:

> The start function accepts the full re-frame context and the value returned from params. It should return nil or an event vector to be dispatched.

Perhaps we could update that to mention or show an example of the two different styles (function vs. vector) which would result in the exact same behavior.

Aside from this, I've really enjoyed using this library, so thanks for making it!

**Comment by ingesolvoll** [comment]
Thank you for the detailed report! I don't have time to look into this right now, but I will do as soon as I can. If the behaviour is in fact inconsistent, we need to consider if correcting it would be breaking backwards compatibility. That would be a very bad thing in this case, and a documentation fix might be the best solution. But we'll see!

**Comment by bschwind** [comment]
I agree that a breaking change wouldn't be worth it, just a small explanatory comment would be helpful I think.

**Comment by ingesolvoll** [comment]
I had some think to think this through. You docs here was an excellent resource in understanding my own code, so thank you for that :)

The main point to me here is:
- Using a function for `:start` gives you flexibility to return the event vector in whatever shape you want. Which makes sense I think.
- With a vector, you trade away flexibility for conciseness and some implicit assumptions. One being that the route params are always passed in. They are passed in because you quite often need them.

I added a note in the readme to cover this. It's probably not enough to prevent confusion, but re-frame param destructuring is a large source of error anyway, so hopefully people will be alert.

Anyway, thank you so much for this very helpful report, hope you will stay productive.

**Comment by bschwind** [comment]
Thanks for the response. I think a comment is the most reasonable thing to do here. Once you know the rule it's quite simple to work with.

Thanks again for the great framework!
