### ISSUE TITLE
Support for default routes

### ISSUE THREAD

**Issue by urzds** [ingesolvoll/kee-frame#72]
It would be nice to have the ability to define a default route, in case no route matches the URL.

Currently, `ReititRouter` in `src/kee_frame/router.cljc` calls `route-match-not-found`, which throws an exception. Maybe it could instead return a default route, in case one is defined in the kee-frame settings?

**Comment by ingesolvoll** [comment]
I think that's a good idea. Will look into it.

**Comment by ingesolvoll** [comment]
Actually, I would think that this is something the router library (Reitit in this case) should handle. There should be wildcard syntax to allow you to catch any url, and use that as your default route. I think most routing libs, including Reitit, support that.
