### ISSUE TITLE
Routes Spec Error When Adding to DB State

### ISSUE THREAD

**Issue by mudgen** [ingesolvoll/kee-frame#73]
I am using kee-from version 0.3.3.

I specify no spec for my db state.

Adding the following to my db state causes the error that is shown below:
```
{:db (assoc db ::mokens [{:tokenid 70, :name " Mokens", :category " Genesis", :url nil}
                               {:tokenid 69, :name " EXCHANGE", :category " Genesis", :url nil}
                               {:tokenid 68, :name " bags", :category " Genesis", :url nil}
                               {:tokenid 67, :name " node", :category " Genesis", :url nil}
                               ])}
```

When the above is executed I get this error:

```
-- Spec failed --------------------

  [... :tokenid ...]
       ^^^^^^^^

should satisfy

  map?

-- Relevant specs -------

:kee-frame.spec/route-data:
  (cljs.spec.alpha/cat
   :route-name
   cljs.core/keyword?
   :path-params
   (cljs.spec.alpha/*
    (cljs.spec.alpha/map-of cljs.core/keyword? cljs.core/any?)))

-------------------------
Detected 1 error

Uncaught #error {:message "Bad route data input", :data {:cljs.spec.alpha/problems [{…}], :cljs.spec.alpha/spec :kee-frame.spec/route-data, :cljs.spec.alpha/value [:moken-item :tokenid 70]}}

```
Adding this state to my db has nothing to do with routes so I don't understand why I am getting this error. Further if I change ::mokens to something else like "::mokensSomethingElse"  then I do not get the error. Please help me fix this. My application depends on the map being named ::mokens.

**Comment by mudgen** [comment]
I found out the cause of the problem.

I was upgrading my application that was using bidi before.  One change is the format for the `path-for` function.  Before I could use this format: (path-for [:moken-item :tokenid tokenid])` which was causing the error.  I changed the format to this to fix the problem: `(path-for [:moken-item {:tokenid tokenid}])`

**Comment by ingesolvoll** [comment]
Hi! Hm, so this might become a problem because it doesn't necessarily play well with different router implementations. The spec now works for reitit, but not bidi. Or am I interpreting this correctly?

**Comment by mudgen** [comment]
Yes, the spec works for reitit, but not bidi.    Yes, it seems like a different spec might be needed depending on which router is used.
