### ISSUE TITLE
Protecting Routes

### ISSUE THREAD

**Issue by j0hnnyblaz3** [ingesolvoll/kee-frame#74]
Hello, I am really enjoying kee-frame! I am working on a project in which there is a login route and other routes that require the user to be logged in. Is there a way to make any route that is not the login route show the login route or re-route to login? 
Thanks!

**Comment by ingesolvoll** [comment]
Hi!

So happy to hear that you are using and enjoying it!

I'm assuming that you want to check for some condition in your client db, and then redirect user to login page if no credentials are present? You could use a kee-frame controller that triggers on every route change, or you could use a re-frame interceptor. There are also patterns to apply from reitit.

**Comment by j0hnnyblaz3** [comment]
Thank you for the response. I went the route of using the controller to navigate-to the login page if the user was not logged in.
