### ISSUE TITLE
Code Splitting

### ISSUE THREAD

**Issue by mudgen** [ingesolvoll/kee-frame#75]
As a kee-frame app gets bigger, having many different web pages, code splitting starts to become important.  How about adding some kind of support or guide for code splitting with kee-frame?

More info here: 
https://code.thheller.com/blog/shadow-cljs/2019/03/03/code-splitting-clojurescript.html

https://clojurescript.org/guides/code-splitting

**Comment by ingesolvoll** [comment]
Love the idea! I think a nice and simple setup for that would be a good fit for kee-frame.

Unfortunately, I'm not likely to be spending much time on it any time soon, so if anyone wants to try a PR is welcome.

**Comment by ingesolvoll** [comment]
Closing this, as I'm unlikely to spend time on it. PRs are welcome
