### ISSUE TITLE
Routing on static SPA

### ISSUE THREAD

**Issue by A-Helberg** [ingesolvoll/kee-frame#77]
The hash-router expects a leading /

When loading a static file, www.example.com/index.html/#/ and file:///some/path/index.html/#/ is invalid.

I've tracked this down to [this file/line](https://github.com/ingesolvoll/kee-frame/blob/bf3a7c3194a32ba20b564523cba0f3df5fba3afc/src/kee_frame/router.cljc#L50)

I am happy to submit a PR where it checks if the url ends in an extensions check without leading slash, otherwise current behaviour, or let me know what you propose :)

My specific use case is an electron app, and the file will always be loaded by path on disk

**Comment by ingesolvoll** [comment]
Would love a PR, but would need to get demo app up and running again to test this against a couple of different configs and browsers.

Do you have thoughts on possible problems that this change could cause?

**Comment by ingesolvoll** [comment]
Are you aware that you can just override this router implementation and fix it in your project code? Just throwing out the question here, did not conclude in any way if this change makes sense for kee-frame or not.

**Comment by A-Helberg** [comment]
I was not aware of that, and I didn't even consider it :)
I can see it's a `(defrecord ReititRouter` but not sure where I would pass my own impl. in.

I'll investigate a proper solution and get back, hopefully over saturday.

**Comment by ingesolvoll** [comment]
https://github.com/ingesolvoll/kee-frame#using-a-different-router-implementation

**Comment by ingesolvoll** [comment]
Might be nice to have a good reference router implementation for electron apps!

**Comment by A-Helberg** [comment]
Absolutely agreed and 🤦‍♂ for me not reading the docs properly.

I'll get something up and running tomorrow and link to it, if you wouldn't mind giving the router a once over?

**Comment by ingesolvoll** [comment]
@A-Helberg Actually, you not needing to read the full docs is good news, means it's easy to get started :) Just let me know if you feel like showing your router version.

**Comment by ingesolvoll** [comment]
Closing this then. Thanks for the interesting example, and good luck on your app!
