### ISSUE TITLE
Don't warn about overwriting controllers when hot-reloading code

### ISSUE THREAD

**Issue by p-himik** [ingesolvoll/kee-frame#81]
A similar issue in `re-frame`: https://github.com/Day8/re-frame/issues/204

A workaround is pretty much the same. And I guess when that issue becomes closed, this one could be closed as well with a similar or same solution.

A side-note: while the warning tells users about overwriting a controller, in fact a merge is happening. I'm not sure if update+merge is supposed to be there instead of simple assoc.

**Comment by ingesolvoll** [comment]
> A similar issue in `re-frame`: [day8/re-frame#204](https://github.com/day8/re-frame/issues/204)
> 
> A workaround is pretty much the same. And I guess when that issue becomes closed, this one could be closed as well with a similar or same solution.

There are a few different things to consider here. There are several types of messages here that could benefit from a more fine tuned config. Starting and stopping of controllers, data diffs etc. I'm considering adding support for a map in the `debug?` config key, so users can pick and choose. What do you think?

> 
> A side-note: while the warning tells users about overwriting a controller, in fact a merge is happening. I'm not sure if update+merge is supposed to be there instead of simple assoc.

You are probably right that it doesn't make much sense to update+merge, don't know why I wrote it that way. Will switch to assoc and see how it works.

**Comment by p-himik** [comment]
> I'm considering adding support for a map in the debug? config key, so users can pick and choose. What do you think?

It's hard to say no for more logging. :)
Although I wouldn't use `:debug?` for this since its name clearly conveys that it should be a boolean. Maybe `:debug-config` or something like that that's ignored if `:debug?` is false-y.
