### ISSUE TITLE
reagent.core/render is deprecated

### ISSUE THREAD

**Issue by p-himik** [ingesolvoll/kee-frame#86]
Deprecated in Reagent 0.10.0.
Used at https://github.com/ingesolvoll/kee-frame/blob/63f3f08002cc4bffb37d669342def8a9b6a4491f/src/kee_frame/interop.cljs#L25
`reagent.dom/render` should be used instead.

**Comment by ingesolvoll** [comment]
@p-himik  Excellent, thanks. Hopefully I will find time to fix and push a new version soon :)
