### ISSUE TITLE
Question regarding reg-controller

### ISSUE THREAD

**Issue by BorisKourt** [ingesolvoll/kee-frame#93]
I feel like I'm misunderstanding something.

Lets say I have two controllers:

```clj
(kf/reg-controller :home
                   {:params (fn [route-data]
                              (-> route-data :data :name (= :home)))
                    :start  (fn [ctx _]
                              (log/info :page :home)
                              [::fetch-home])})

(kf/reg-controller :docs
                   {:params (fn [route-data]
                              (-> route-data :data :name (= :docs)))
                    :start  (fn [ctx _]
                              (log/info :page :docs)
                              [::fetch-md])})
```

My expectation is that if I load `:home` I would only see `{:page :home, :line 176}` from the logging library. But I am seeing both `:home` and `:docs`. 

If I continue to navigate to `:docs` I again see both `:home` and `:docs`.  And vice versa.

Is `:start` called on both `:start` and "leave"?

***

As an aside, I notice this guard in the docs:

```clj
(when (-> route-data :data :name (= :league))
                               (-> route-data
                                   :path-params
                                   :id))
```

If the controller is registered as `:league` what is the purpose of the `(-> route-data :data :name (= :league))` above?

Sorry for the question instead of an issue.

**Comment by schpaa** [comment]
I guess it’s to ensure that the controller is only started _when_ the predicate is true? And then sends the following expression to the second argument of :start ...

**Comment by BorisKourt** [comment]
Hey, thanks for your reply. The problem I am seeing is that it doesn't seem to matter whether the predicate is true. In the case above both `:home` and `:docs` appear to fire every time. 

I also note the following in [this blog post](https://ingesolvoll.github.io/posts/2018-04-01-learning-kee-frame-in-5-minutes/):

```clj
(reg-controller :league ;; <- is this just a name?
                {:params (fn [{:keys [handler route-params]}]
                           (when (= handler :league) ;; <- is the fact that this keyword is the same unrelated?
                             (:id route-params)))
                 :start  [:league/load]})
```

Did I misunderstand controllers in that they don't fire based on the routes switching but rather they work in the way that mount or component libraries work and all trigger in a specific order?

**Comment by ingesolvoll** [comment]
@BorisKourt If your `:params` returns false, that will trigger a controller start. I know this sounds strange, but it opens up for using `false` as a meaningful value for controllers. So the solution is to add `nil` to the end of your `:params` function. If I understood the problem correctly.

**Comment by ingesolvoll** [comment]
Thanks for posting such an elaborate and clean report, made it very easy to follow up.

**Comment by ingesolvoll** [comment]
The controller rules are explicit about this, but I think maybe this should be made clearer in the docs. Let's keep the issue open to see if we can fix that 

https://github.com/ingesolvoll/kee-frame#controller-state-transitions

**Comment by BorisKourt** [comment]
Thanks for your reply. That is appears to be exactly my misunderstanding. Its likely that since I haven't had experience with Keechma, I didn't have the intuition for this.

I'll try to think of a some ways to provide additional hints for others reading the docs.

**Comment by ingesolvoll** [comment]
Considered fixed with https://github.com/ingesolvoll/kee-frame/commit/6eac8c940142e284c839a8bfb830df1c3c6db32f
