### ISSUE TITLE
Upgrade com.taoensso/timbre dep to avoid compilation warnings

### ISSUE THREAD

**Issue by kyptin** [ingesolvoll/kee-frame#99]
Hey, thanks for the nice library. :-)

You're currently depending on version 4.10.0 of `com.taoensso/timbre`, which depends on version 2.91.0 of `com.taoensso/encore`, which prints the following warnings during CLJS compilation:

```
[Figwheel:WARNING] Compile Warning   target/public/cljs-out/min-e2etest/taoensso/encore.cljs   line:2683  column:16

  Use of undeclared Var goog.structs/Map

  2678    (def ^:private coerce-xhr-params "Returns [<uri> <?data>]"
  2679      (let [url-encode
  2680            (fn url-encode
  2681              ([params]
  2682               (when (seq params)
  2683                 (-> params clj->js gstructs/Map. gquery-data/createFromMap .toString)))
                       ^---
  2684
  2685              ([uri params]
  2686               (let [qstr (url-encode params)
  2687                     uri-with-query (if (str/blank? qstr) uri (str uri "?" qstr))]
  2688                 [uri-with-query nil])))

[Figwheel:WARNING] Compile Warning   target/public/cljs-out/min-e2etest/taoensso/encore.cljs   line:2683  column:16

  Use of undeclared Var goog.structs/Map

  2678    (def ^:private coerce-xhr-params "Returns [<uri> <?data>]"
  2679      (let [url-encode
  2680            (fn url-encode
  2681              ([params]
  2682               (when (seq params)
  2683                 (-> params clj->js gstructs/Map. gquery-data/createFromMap .toString)))
                       ^---
  2684
  2685              ([uri params]
  2686               (let [qstr (url-encode params)
  2687                     uri-with-query (if (str/blank? qstr) uri (str uri "?" qstr))]
  2688                 [uri-with-query nil])))
```

These warnings are noted in [this issue in the encore repo](https://github.com/ptaoussanis/encore/issues/47).

The fix for users of kee-frame is simple: upgrade to version 5.1.0 of `com.taoensso/timbre`. [The changelog](https://github.com/ptaoussanis/timbre/releases) doesn't seem to have anything that would likely affect kee-frame users. I added this version of timbre to my project and didn't have any issues.

Relatedly, [looks like](https://day8.github.io/re-frame/releases/2020/) re-frame version 1.1.2 is out, so this change could be included with a new kee-frame version 1.1.2.

**Comment by ingesolvoll** [comment]
Thank you for reporting! Will try to get to it in the coming weeks. PR welcome if you feel up for it.

**Comment by ingesolvoll** [comment]
Seems to work just fine, releasing!
